spring.application.name=jpa
# está no disco virtual, pasta
# 01_bimestre/09_aula
# Conexão MySQL
spring.datasource.url = jdbc:mysql://localhost:3306/meu_db
spring.datasource.username = root
spring.datasource.password = admin
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

# Configurações do JPA and Hibernate
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
